# Generated by Django 3.2.4 on 2021-07-06 12:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('ecg_signal', models.FileField(upload_to=core.models.Patient.get_path_upload)),
                ('added', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ECGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arythmia_type', models.CharField(blank=True, choices=[(0, 'Normal beat'), (1, 'Left bundle branch block beat'), (2, 'Premature ventricular contraction'), (3, 'Right bundle branch block beat'), (4, 'Atrial premature beat')], max_length=50, null=True)),
                ('signal', models.ImageField(upload_to='media/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
